#!/usr/bin/env bash
# The Script transfers a file from a client to a
# remote server using scp

# Checj the number of parameters provided

if ["$#" -lt 3]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif ["$#" -lt 4]; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2":~/
else
	scp -i "$1" StrictHostKeyChecking=no "$1" "$3@$2":~/
fi
