#!/usr/bin/env bash
#A Bash script that transfers a file from our client to a server.
# Check if the correct number of args has been provided.
if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi
#Assign args to vars
path_to_file="$1"
server_address="$2"
server_username="$3"
private_key="$4"

#Perform file transfer
scp -o StrictHostKeyChecking=no -i "$private_key" "$path_to_file" "$server_username"@"$server_address":~/

#Check the exit status of scp
if [ "$?" -eq 0 ]; then
    echo "File transfer successful."
else
    echo "File transfer unsuccessful."
fi