#!/usr/bin/env bash
#The script installs nginx package and ensures its listening on port 80
# Update the package list to ensure you have the latest information about available packages

sudo apt update
sudo apt-get install -y nginx
sudo chown -R ubuntu /var/www
echo "Hello World!" > /var/www/html/index.nginx-debain.html

sudo service nginx start

# Configure Nginx to listen on port 80 and serve the custom HTML file
#sudo bash -c 'echo "server {
	#listen 80 default_server;
	#listen [::]:80 default_server;
	
	#root /var/www/html;
	#index index.html;
	
	#location / {
		#try_files $uri $uri/ =404;
	#}
#}" > /etc/nginx/sites-available/default'
