#!/usr/bin/env bash
#The script installs an nginx web server that is
#configured to listen on port 80

apt-get update
apt-get -y install nginx
service nginx start

echo "Hello Workd!" > /var/www/html/index.html
