#!/usr/bin/env bash
#Configure nginx to have a custom 404 page that contains 'Ceci n'est pas une page'
sudo apt-get update
sudo apt-get install -y nginx
#Set up the firewall
sudo ufw allow 'Nginx HTTP'
chmod -R 755 /var/www
echo "Hello World!" | sudo tee /var/www/html/index.html

new_config=\
"server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files $uri $uri/ =404;
        }
        error_page 404 /404.html;
        location /404.html{
            internal;
        }
        if (\$request_filename ~ redirect_me){
            rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
        }
}"
echo "Ceci n'est pas une page" > /var/www/html/404.html
echo "$new_config" > /etc/nginx/sites-available/default
if [ "$(pgrep nginx)" -le 0];
then
    sudo service nginx start
else
    sudo service nginx restart
fi