#!/usr/bin/env bash
# Configure web-02 server to be like web-01 and both should include the,
# custom header  X-Served-By
# Update packages and install nginx
sudo apt update
sudo apt install -y nginx

# Create a page with the words "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Perform redirection 
conf="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/Wanjiruwanjiku-tech permanent"
sudo sed -i "s/server_name _;/$conf/" /etc/nginx/sites-enabled/default

# Custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# Add the custom http header 
sudo sed -i "/server_name _/a add_header X-Served-By $(hostname);" /etc/nginx/sites-enabled/default

# Test nginx for errors
sudo nginx -t

# Restart to apply changes
sudo service nginx restart