#!/usr/bin/env bash
# The script configures web-02 server to match web-01 server

#First Install required software (e.g., Nginx)
sudo apt-get update
sudo apt-get install -y nginx

# Copy the Nginx configuration from web-01 to web-02
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/web-02
sudo ln -sf /etc/nginx/sites-available/web-02 /etc/nginx/sites-enabled/

# Creating the http custom header
echo 'server {
    location / {
        add_header X-Served-By $hostname;
    }
}' | sudo tee /etc/nginx/sites-available/web-01

# Reload Nginx to apply the changes
sudo service nginx reload
