#!/usr/bin/env bash
# The script runs configurations to ensure that nginx is listening on port 80
# for all the server's active IPv4 ips
# Install nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

# Backup the default nginx cofiguration file
cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

#Remove the default nginx configuration file
sudo rm -r /etc/nginx/sites-enabled/default

# Modify the default configuration file to listen on port 80
sed -i 's/\blisten 80;/listen 80 default_server;/g' /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart nginx to apply changes
sudo service nginx restart

#Verify that nginx is now listening on port 80
curl 0:80