#!/usr/bin/env bash
#A Script that Displays time using a while loop

hour=0
minute=1
while [ $hour -lt 12 ]
do
	echo "Hour: $hour"
	while [ $minute -le 59 ]
	do
		echo $minute
		minute=$((minute + 1))
	done

	hour=$((hour + 1))
	minute=0
done
