#!/usr/bin/env bash
#Displays the contents of a directory in list format

for file in *
do
	if [[ ! "$file" =~ ^\. && -f "$file" ]]
	then
		name=$(echo "$file" | cut -d '-' -f 2-)
		echo "$name"
	fi
done
