#!/usr/bin/env bash
#A Bash script that configures an Ubuntu server with
#the below requirements.
#Requirements:
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.

cp /etc/hosts ~/hosts.new

#Created a backup copy of /etc/hosts and saved it in
#the users home directory rep by '~'

echo "127.0.0.2 localhost" > ~/hosts.new

#Redirect output to the specified file using '>'

echo "8.8.8.8 facebook.com" >> ~/hosts.new

#Appends another line to '~/hosts.new' using '>>'

cp -f ~/hosts.new /etc/hosts

#Replaces the original file '/etc/hosts' contents
#with the modified contents in '~/hosts.new'
#The -f flag forces the replacement
